packages:
  - 'apps/*'
  - 'packages/*'
catalog:
  '@types/node': '^26.4.1'
  '@types/react': '^19'
  '@types/react-dom': '^19'
  '@vitejs/plugin-react': '^6.0.1'
  'react': '^19'
  'react-dom': '^19'
  'tailwind-variants': '^3.2.2'
  'tailwindcss': '^4.2.1'
  'typescript': '7.0.2'
  'vite': '^8.0.10'
  'vitest': '^5.0.0'
  'zustand': '^5.0.11'
allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  esbuild: true
  nx: true
  sharp: true
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.0'
  - '@vitest/spy@5.0.0'
  - vitest@5.0.0
