/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as AuthenticatedSlugIndexRouteImport } from './routes/_authenticated/$slug/index'
import { Route as AuthenticatedSlugPlansRouteImport } from './routes/_authenticated/$slug/plans'
import { Route as AuthenticatedSlugTodosRouteImport } from './routes/_authenticated/$slug/todos'
import { Route as AuthenticatedSlugDocsIndexRouteImport } from './routes/_authenticated/$slug/docs/index'
import { Route as AuthenticatedSlugDocsDocRouteImport } from './routes/_authenticated/$slug/docs/$doc'
import { Route as AuthenticatedSlugJournalIndexRouteImport } from './routes/_authenticated/$slug/journal/index'
import { Route as AuthenticatedSlugJournalEntryRouteImport } from './routes/_authenticated/$slug/journal/$entry'
import { Route as AuthenticatedSlugTicketsIndexRouteImport } from './routes/_authenticated/$slug/tickets/index'
import { Route as AuthenticatedSlugTicketsTicketRouteImport } from './routes/_authenticated/$slug/tickets/$ticket'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugIndexRoute = AuthenticatedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugPlansRoute = AuthenticatedSlugPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugTodosRoute = AuthenticatedSlugTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugDocsIndexRoute =
  AuthenticatedSlugDocsIndexRouteImport.update({
    id: '/docs/',
    path: '/docs/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocsDocRoute =
  AuthenticatedSlugDocsDocRouteImport.update({
    id: '/docs/$doc',
    path: '/docs/$doc',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugJournalIndexRoute =
  AuthenticatedSlugJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugJournalEntryRoute =
  AuthenticatedSlugJournalEntryRouteImport.update({
    id: '/journal/$entry',
    path: '/journal/$entry',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTicketsIndexRoute =
  AuthenticatedSlugTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugTicketsTicketRoute =
  AuthenticatedSlugTicketsTicketRouteImport.update({
    id: '/tickets/$ticket',
    path: '/tickets/$ticket',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/$slug/plans': typeof AuthenticatedSlugPlansRoute
  '/$slug/todos': typeof AuthenticatedSlugTodosRoute
  '/$slug/': typeof AuthenticatedSlugIndexRoute
  '/$slug/docs/$doc': typeof AuthenticatedSlugDocsDocRoute
  '/$slug/journal/$entry': typeof AuthenticatedSlugJournalEntryRoute
  '/$slug/tickets/$ticket': typeof AuthenticatedSlugTicketsTicketRoute
  '/$slug/docs/': typeof AuthenticatedSlugDocsIndexRoute
  '/$slug/journal/': typeof AuthenticatedSlugJournalIndexRoute
  '/$slug/tickets/': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/$slug/plans': typeof AuthenticatedSlugPlansRoute
  '/$slug/todos': typeof AuthenticatedSlugTodosRoute
  '/$slug': typeof AuthenticatedSlugIndexRoute
  '/$slug/docs/$doc': typeof AuthenticatedSlugDocsDocRoute
  '/$slug/journal/$entry': typeof AuthenticatedSlugJournalEntryRoute
  '/$slug/tickets/$ticket': typeof AuthenticatedSlugTicketsTicketRoute
  '/$slug/docs': typeof AuthenticatedSlugDocsIndexRoute
  '/$slug/journal': typeof AuthenticatedSlugJournalIndexRoute
  '/$slug/tickets': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$slug/plans': typeof AuthenticatedSlugPlansRoute
  '/_authenticated/$slug/todos': typeof AuthenticatedSlugTodosRoute
  '/_authenticated/$slug/': typeof AuthenticatedSlugIndexRoute
  '/_authenticated/$slug/docs/$doc': typeof AuthenticatedSlugDocsDocRoute
  '/_authenticated/$slug/journal/$entry': typeof AuthenticatedSlugJournalEntryRoute
  '/_authenticated/$slug/tickets/$ticket': typeof AuthenticatedSlugTicketsTicketRoute
  '/_authenticated/$slug/docs/': typeof AuthenticatedSlugDocsIndexRoute
  '/_authenticated/$slug/journal/': typeof AuthenticatedSlugJournalIndexRoute
  '/_authenticated/$slug/tickets/': typeof AuthenticatedSlugTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$slug'
    | '/$slug/plans'
    | '/$slug/todos'
    | '/$slug/'
    | '/$slug/docs/$doc'
    | '/$slug/journal/$entry'
    | '/$slug/tickets/$ticket'
    | '/$slug/docs/'
    | '/$slug/journal/'
    | '/$slug/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/$slug/plans'
    | '/$slug/todos'
    | '/$slug'
    | '/$slug/docs/$doc'
    | '/$slug/journal/$entry'
    | '/$slug/tickets/$ticket'
    | '/$slug/docs'
    | '/$slug/journal'
    | '/$slug/tickets'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$slug'
    | '/_authenticated/'
    | '/_authenticated/$slug/plans'
    | '/_authenticated/$slug/todos'
    | '/_authenticated/$slug/'
    | '/_authenticated/$slug/docs/$doc'
    | '/_authenticated/$slug/journal/$entry'
    | '/_authenticated/$slug/tickets/$ticket'
    | '/_authenticated/$slug/docs/'
    | '/_authenticated/$slug/journal/'
    | '/_authenticated/$slug/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug/': {
      id: '/_authenticated/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthenticatedSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/plans': {
      id: '/_authenticated/$slug/plans'
      path: '/plans'
      fullPath: '/$slug/plans'
      preLoaderRoute: typeof AuthenticatedSlugPlansRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/todos': {
      id: '/_authenticated/$slug/todos'
      path: '/todos'
      fullPath: '/$slug/todos'
      preLoaderRoute: typeof AuthenticatedSlugTodosRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/docs/': {
      id: '/_authenticated/$slug/docs/'
      path: '/docs'
      fullPath: '/$slug/docs/'
      preLoaderRoute: typeof AuthenticatedSlugDocsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/docs/$doc': {
      id: '/_authenticated/$slug/docs/$doc'
      path: '/docs/$doc'
      fullPath: '/$slug/docs/$doc'
      preLoaderRoute: typeof AuthenticatedSlugDocsDocRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/journal/': {
      id: '/_authenticated/$slug/journal/'
      path: '/journal'
      fullPath: '/$slug/journal/'
      preLoaderRoute: typeof AuthenticatedSlugJournalIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/journal/$entry': {
      id: '/_authenticated/$slug/journal/$entry'
      path: '/journal/$entry'
      fullPath: '/$slug/journal/$entry'
      preLoaderRoute: typeof AuthenticatedSlugJournalEntryRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/tickets/': {
      id: '/_authenticated/$slug/tickets/'
      path: '/tickets'
      fullPath: '/$slug/tickets/'
      preLoaderRoute: typeof AuthenticatedSlugTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/tickets/$ticket': {
      id: '/_authenticated/$slug/tickets/$ticket'
      path: '/tickets/$ticket'
      fullPath: '/$slug/tickets/$ticket'
      preLoaderRoute: typeof AuthenticatedSlugTicketsTicketRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
  }
}

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugPlansRoute: typeof AuthenticatedSlugPlansRoute
  AuthenticatedSlugTodosRoute: typeof AuthenticatedSlugTodosRoute
  AuthenticatedSlugIndexRoute: typeof AuthenticatedSlugIndexRoute
  AuthenticatedSlugDocsDocRoute: typeof AuthenticatedSlugDocsDocRoute
  AuthenticatedSlugJournalEntryRoute: typeof AuthenticatedSlugJournalEntryRoute
  AuthenticatedSlugTicketsTicketRoute: typeof AuthenticatedSlugTicketsTicketRoute
  AuthenticatedSlugDocsIndexRoute: typeof AuthenticatedSlugDocsIndexRoute
  AuthenticatedSlugJournalIndexRoute: typeof AuthenticatedSlugJournalIndexRoute
  AuthenticatedSlugTicketsIndexRoute: typeof AuthenticatedSlugTicketsIndexRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugPlansRoute: AuthenticatedSlugPlansRoute,
  AuthenticatedSlugTodosRoute: AuthenticatedSlugTodosRoute,
  AuthenticatedSlugIndexRoute: AuthenticatedSlugIndexRoute,
  AuthenticatedSlugDocsDocRoute: AuthenticatedSlugDocsDocRoute,
  AuthenticatedSlugJournalEntryRoute: AuthenticatedSlugJournalEntryRoute,
  AuthenticatedSlugTicketsTicketRoute: AuthenticatedSlugTicketsTicketRoute,
  AuthenticatedSlugDocsIndexRoute: AuthenticatedSlugDocsIndexRoute,
  AuthenticatedSlugJournalIndexRoute: AuthenticatedSlugJournalIndexRoute,
  AuthenticatedSlugTicketsIndexRoute: AuthenticatedSlugTicketsIndexRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
