/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/$client'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/$client/index'
import { Route as AuthenticatedClientDomainRouteImport } from './routes/_authenticated/$client/$domain'
import { Route as AuthenticatedClientDomainIndexRouteImport } from './routes/_authenticated/$client/$domain/index'
import { Route as AuthenticatedClientDomainSlugRouteImport } from './routes/_authenticated/$client/$domain/$slug'
import { Route as AuthenticatedClientDomainSlugIndexRouteImport } from './routes/_authenticated/$client/$domain/$slug/index'
import { Route as AuthenticatedClientDomainSlugTodosRouteImport } from './routes/_authenticated/$client/$domain/$slug/todos'
import { Route as AuthenticatedClientDomainSlugDocsIndexRouteImport } from './routes/_authenticated/$client/$domain/$slug/docs/index'
import { Route as AuthenticatedClientDomainSlugDocsDocRouteImport } from './routes/_authenticated/$client/$domain/$slug/docs/$doc'
import { Route as AuthenticatedClientDomainSlugJournalIndexRouteImport } from './routes/_authenticated/$client/$domain/$slug/journal/index'
import { Route as AuthenticatedClientDomainSlugJournalEntryRouteImport } from './routes/_authenticated/$client/$domain/$slug/journal/$entry'
import { Route as AuthenticatedClientDomainSlugPlansIndexRouteImport } from './routes/_authenticated/$client/$domain/$slug/plans/index'
import { Route as AuthenticatedClientDomainSlugPlansPlanRouteImport } from './routes/_authenticated/$client/$domain/$slug/plans/$plan'
import { Route as AuthenticatedClientDomainSlugTicketsIndexRouteImport } from './routes/_authenticated/$client/$domain/$slug/tickets/index'
import { Route as AuthenticatedClientDomainSlugTicketsTicketRouteImport } from './routes/_authenticated/$client/$domain/$slug/tickets/$ticket'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/$client',
  path: '/$client',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDomainRoute =
  AuthenticatedClientDomainRouteImport.update({
    id: '/$domain',
    path: '/$domain',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientDomainIndexRoute =
  AuthenticatedClientDomainIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientDomainRoute,
  } as any)
const AuthenticatedClientDomainSlugRoute =
  AuthenticatedClientDomainSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedClientDomainRoute,
  } as any)
const AuthenticatedClientDomainSlugIndexRoute =
  AuthenticatedClientDomainSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugTodosRoute =
  AuthenticatedClientDomainSlugTodosRouteImport.update({
    id: '/todos',
    path: '/todos',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugDocsIndexRoute =
  AuthenticatedClientDomainSlugDocsIndexRouteImport.update({
    id: '/docs/',
    path: '/docs/',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugDocsDocRoute =
  AuthenticatedClientDomainSlugDocsDocRouteImport.update({
    id: '/docs/$doc',
    path: '/docs/$doc',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugJournalIndexRoute =
  AuthenticatedClientDomainSlugJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugJournalEntryRoute =
  AuthenticatedClientDomainSlugJournalEntryRouteImport.update({
    id: '/journal/$entry',
    path: '/journal/$entry',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugPlansIndexRoute =
  AuthenticatedClientDomainSlugPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugPlansPlanRoute =
  AuthenticatedClientDomainSlugPlansPlanRouteImport.update({
    id: '/plans/$plan',
    path: '/plans/$plan',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugTicketsIndexRoute =
  AuthenticatedClientDomainSlugTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)
const AuthenticatedClientDomainSlugTicketsTicketRoute =
  AuthenticatedClientDomainSlugTicketsTicketRouteImport.update({
    id: '/tickets/$ticket',
    path: '/tickets/$ticket',
    getParentRoute: () => AuthenticatedClientDomainSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/$client': typeof AuthenticatedClientRouteWithChildren
  '/$client/$domain': typeof AuthenticatedClientDomainRouteWithChildren
  '/$client/': typeof AuthenticatedClientIndexRoute
  '/$client/$domain/$slug': typeof AuthenticatedClientDomainSlugRouteWithChildren
  '/$client/$domain/': typeof AuthenticatedClientDomainIndexRoute
  '/$client/$domain/$slug/todos': typeof AuthenticatedClientDomainSlugTodosRoute
  '/$client/$domain/$slug/': typeof AuthenticatedClientDomainSlugIndexRoute
  '/$client/$domain/$slug/docs/$doc': typeof AuthenticatedClientDomainSlugDocsDocRoute
  '/$client/$domain/$slug/journal/$entry': typeof AuthenticatedClientDomainSlugJournalEntryRoute
  '/$client/$domain/$slug/plans/$plan': typeof AuthenticatedClientDomainSlugPlansPlanRoute
  '/$client/$domain/$slug/tickets/$ticket': typeof AuthenticatedClientDomainSlugTicketsTicketRoute
  '/$client/$domain/$slug/docs/': typeof AuthenticatedClientDomainSlugDocsIndexRoute
  '/$client/$domain/$slug/journal/': typeof AuthenticatedClientDomainSlugJournalIndexRoute
  '/$client/$domain/$slug/plans/': typeof AuthenticatedClientDomainSlugPlansIndexRoute
  '/$client/$domain/$slug/tickets/': typeof AuthenticatedClientDomainSlugTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/$client': typeof AuthenticatedClientIndexRoute
  '/$client/$domain': typeof AuthenticatedClientDomainIndexRoute
  '/$client/$domain/$slug/todos': typeof AuthenticatedClientDomainSlugTodosRoute
  '/$client/$domain/$slug': typeof AuthenticatedClientDomainSlugIndexRoute
  '/$client/$domain/$slug/docs/$doc': typeof AuthenticatedClientDomainSlugDocsDocRoute
  '/$client/$domain/$slug/journal/$entry': typeof AuthenticatedClientDomainSlugJournalEntryRoute
  '/$client/$domain/$slug/plans/$plan': typeof AuthenticatedClientDomainSlugPlansPlanRoute
  '/$client/$domain/$slug/tickets/$ticket': typeof AuthenticatedClientDomainSlugTicketsTicketRoute
  '/$client/$domain/$slug/docs': typeof AuthenticatedClientDomainSlugDocsIndexRoute
  '/$client/$domain/$slug/journal': typeof AuthenticatedClientDomainSlugJournalIndexRoute
  '/$client/$domain/$slug/plans': typeof AuthenticatedClientDomainSlugPlansIndexRoute
  '/$client/$domain/$slug/tickets': typeof AuthenticatedClientDomainSlugTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/$client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$client/$domain': typeof AuthenticatedClientDomainRouteWithChildren
  '/_authenticated/$client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/$client/$domain/$slug': typeof AuthenticatedClientDomainSlugRouteWithChildren
  '/_authenticated/$client/$domain/': typeof AuthenticatedClientDomainIndexRoute
  '/_authenticated/$client/$domain/$slug/todos': typeof AuthenticatedClientDomainSlugTodosRoute
  '/_authenticated/$client/$domain/$slug/': typeof AuthenticatedClientDomainSlugIndexRoute
  '/_authenticated/$client/$domain/$slug/docs/$doc': typeof AuthenticatedClientDomainSlugDocsDocRoute
  '/_authenticated/$client/$domain/$slug/journal/$entry': typeof AuthenticatedClientDomainSlugJournalEntryRoute
  '/_authenticated/$client/$domain/$slug/plans/$plan': typeof AuthenticatedClientDomainSlugPlansPlanRoute
  '/_authenticated/$client/$domain/$slug/tickets/$ticket': typeof AuthenticatedClientDomainSlugTicketsTicketRoute
  '/_authenticated/$client/$domain/$slug/docs/': typeof AuthenticatedClientDomainSlugDocsIndexRoute
  '/_authenticated/$client/$domain/$slug/journal/': typeof AuthenticatedClientDomainSlugJournalIndexRoute
  '/_authenticated/$client/$domain/$slug/plans/': typeof AuthenticatedClientDomainSlugPlansIndexRoute
  '/_authenticated/$client/$domain/$slug/tickets/': typeof AuthenticatedClientDomainSlugTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$client'
    | '/$client/$domain'
    | '/$client/'
    | '/$client/$domain/$slug'
    | '/$client/$domain/'
    | '/$client/$domain/$slug/todos'
    | '/$client/$domain/$slug/'
    | '/$client/$domain/$slug/docs/$doc'
    | '/$client/$domain/$slug/journal/$entry'
    | '/$client/$domain/$slug/plans/$plan'
    | '/$client/$domain/$slug/tickets/$ticket'
    | '/$client/$domain/$slug/docs/'
    | '/$client/$domain/$slug/journal/'
    | '/$client/$domain/$slug/plans/'
    | '/$client/$domain/$slug/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/$client'
    | '/$client/$domain'
    | '/$client/$domain/$slug/todos'
    | '/$client/$domain/$slug'
    | '/$client/$domain/$slug/docs/$doc'
    | '/$client/$domain/$slug/journal/$entry'
    | '/$client/$domain/$slug/plans/$plan'
    | '/$client/$domain/$slug/tickets/$ticket'
    | '/$client/$domain/$slug/docs'
    | '/$client/$domain/$slug/journal'
    | '/$client/$domain/$slug/plans'
    | '/$client/$domain/$slug/tickets'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$client'
    | '/_authenticated/'
    | '/_authenticated/$client/$domain'
    | '/_authenticated/$client/'
    | '/_authenticated/$client/$domain/$slug'
    | '/_authenticated/$client/$domain/'
    | '/_authenticated/$client/$domain/$slug/todos'
    | '/_authenticated/$client/$domain/$slug/'
    | '/_authenticated/$client/$domain/$slug/docs/$doc'
    | '/_authenticated/$client/$domain/$slug/journal/$entry'
    | '/_authenticated/$client/$domain/$slug/plans/$plan'
    | '/_authenticated/$client/$domain/$slug/tickets/$ticket'
    | '/_authenticated/$client/$domain/$slug/docs/'
    | '/_authenticated/$client/$domain/$slug/journal/'
    | '/_authenticated/$client/$domain/$slug/plans/'
    | '/_authenticated/$client/$domain/$slug/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$client': {
      id: '/_authenticated/$client'
      path: '/$client'
      fullPath: '/$client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$client/': {
      id: '/_authenticated/$client/'
      path: '/'
      fullPath: '/$client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/$client/$domain': {
      id: '/_authenticated/$client/$domain'
      path: '/$domain'
      fullPath: '/$client/$domain'
      preLoaderRoute: typeof AuthenticatedClientDomainRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/$client/$domain/': {
      id: '/_authenticated/$client/$domain/'
      path: '/'
      fullPath: '/$client/$domain/'
      preLoaderRoute: typeof AuthenticatedClientDomainIndexRouteImport
      parentRoute: typeof AuthenticatedClientDomainRoute
    }
    '/_authenticated/$client/$domain/$slug': {
      id: '/_authenticated/$client/$domain/$slug'
      path: '/$slug'
      fullPath: '/$client/$domain/$slug'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugRouteImport
      parentRoute: typeof AuthenticatedClientDomainRoute
    }
    '/_authenticated/$client/$domain/$slug/': {
      id: '/_authenticated/$client/$domain/$slug/'
      path: '/'
      fullPath: '/$client/$domain/$slug/'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugIndexRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/todos': {
      id: '/_authenticated/$client/$domain/$slug/todos'
      path: '/todos'
      fullPath: '/$client/$domain/$slug/todos'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugTodosRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/docs/': {
      id: '/_authenticated/$client/$domain/$slug/docs/'
      path: '/docs'
      fullPath: '/$client/$domain/$slug/docs/'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugDocsIndexRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/docs/$doc': {
      id: '/_authenticated/$client/$domain/$slug/docs/$doc'
      path: '/docs/$doc'
      fullPath: '/$client/$domain/$slug/docs/$doc'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugDocsDocRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/journal/': {
      id: '/_authenticated/$client/$domain/$slug/journal/'
      path: '/journal'
      fullPath: '/$client/$domain/$slug/journal/'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugJournalIndexRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/journal/$entry': {
      id: '/_authenticated/$client/$domain/$slug/journal/$entry'
      path: '/journal/$entry'
      fullPath: '/$client/$domain/$slug/journal/$entry'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugJournalEntryRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/plans/': {
      id: '/_authenticated/$client/$domain/$slug/plans/'
      path: '/plans'
      fullPath: '/$client/$domain/$slug/plans/'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugPlansIndexRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/plans/$plan': {
      id: '/_authenticated/$client/$domain/$slug/plans/$plan'
      path: '/plans/$plan'
      fullPath: '/$client/$domain/$slug/plans/$plan'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugPlansPlanRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/tickets/': {
      id: '/_authenticated/$client/$domain/$slug/tickets/'
      path: '/tickets'
      fullPath: '/$client/$domain/$slug/tickets/'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
    '/_authenticated/$client/$domain/$slug/tickets/$ticket': {
      id: '/_authenticated/$client/$domain/$slug/tickets/$ticket'
      path: '/tickets/$ticket'
      fullPath: '/$client/$domain/$slug/tickets/$ticket'
      preLoaderRoute: typeof AuthenticatedClientDomainSlugTicketsTicketRouteImport
      parentRoute: typeof AuthenticatedClientDomainSlugRoute
    }
  }
}

interface AuthenticatedClientDomainSlugRouteChildren {
  AuthenticatedClientDomainSlugTodosRoute: typeof AuthenticatedClientDomainSlugTodosRoute
  AuthenticatedClientDomainSlugIndexRoute: typeof AuthenticatedClientDomainSlugIndexRoute
  AuthenticatedClientDomainSlugDocsDocRoute: typeof AuthenticatedClientDomainSlugDocsDocRoute
  AuthenticatedClientDomainSlugJournalEntryRoute: typeof AuthenticatedClientDomainSlugJournalEntryRoute
  AuthenticatedClientDomainSlugPlansPlanRoute: typeof AuthenticatedClientDomainSlugPlansPlanRoute
  AuthenticatedClientDomainSlugTicketsTicketRoute: typeof AuthenticatedClientDomainSlugTicketsTicketRoute
  AuthenticatedClientDomainSlugDocsIndexRoute: typeof AuthenticatedClientDomainSlugDocsIndexRoute
  AuthenticatedClientDomainSlugJournalIndexRoute: typeof AuthenticatedClientDomainSlugJournalIndexRoute
  AuthenticatedClientDomainSlugPlansIndexRoute: typeof AuthenticatedClientDomainSlugPlansIndexRoute
  AuthenticatedClientDomainSlugTicketsIndexRoute: typeof AuthenticatedClientDomainSlugTicketsIndexRoute
}

const AuthenticatedClientDomainSlugRouteChildren: AuthenticatedClientDomainSlugRouteChildren =
  {
    AuthenticatedClientDomainSlugTodosRoute:
      AuthenticatedClientDomainSlugTodosRoute,
    AuthenticatedClientDomainSlugIndexRoute:
      AuthenticatedClientDomainSlugIndexRoute,
    AuthenticatedClientDomainSlugDocsDocRoute:
      AuthenticatedClientDomainSlugDocsDocRoute,
    AuthenticatedClientDomainSlugJournalEntryRoute:
      AuthenticatedClientDomainSlugJournalEntryRoute,
    AuthenticatedClientDomainSlugPlansPlanRoute:
      AuthenticatedClientDomainSlugPlansPlanRoute,
    AuthenticatedClientDomainSlugTicketsTicketRoute:
      AuthenticatedClientDomainSlugTicketsTicketRoute,
    AuthenticatedClientDomainSlugDocsIndexRoute:
      AuthenticatedClientDomainSlugDocsIndexRoute,
    AuthenticatedClientDomainSlugJournalIndexRoute:
      AuthenticatedClientDomainSlugJournalIndexRoute,
    AuthenticatedClientDomainSlugPlansIndexRoute:
      AuthenticatedClientDomainSlugPlansIndexRoute,
    AuthenticatedClientDomainSlugTicketsIndexRoute:
      AuthenticatedClientDomainSlugTicketsIndexRoute,
  }

const AuthenticatedClientDomainSlugRouteWithChildren =
  AuthenticatedClientDomainSlugRoute._addFileChildren(
    AuthenticatedClientDomainSlugRouteChildren,
  )

interface AuthenticatedClientDomainRouteChildren {
  AuthenticatedClientDomainSlugRoute: typeof AuthenticatedClientDomainSlugRouteWithChildren
  AuthenticatedClientDomainIndexRoute: typeof AuthenticatedClientDomainIndexRoute
}

const AuthenticatedClientDomainRouteChildren: AuthenticatedClientDomainRouteChildren =
  {
    AuthenticatedClientDomainSlugRoute:
      AuthenticatedClientDomainSlugRouteWithChildren,
    AuthenticatedClientDomainIndexRoute: AuthenticatedClientDomainIndexRoute,
  }

const AuthenticatedClientDomainRouteWithChildren =
  AuthenticatedClientDomainRoute._addFileChildren(
    AuthenticatedClientDomainRouteChildren,
  )

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientDomainRoute: typeof AuthenticatedClientDomainRouteWithChildren
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientDomainRoute: AuthenticatedClientDomainRouteWithChildren,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
